
spring:
  datasource:
    url: jdbc:mysql://107.191.52.220:3306/bookshop?requireSSL=true&useSSL=true&verifyServerCertificate=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root0101
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: "cn.edu.scut.bookshop.domain.pojo"
#  configuration:
#    interceptors: ["com.github.pagehelper.PageInterceptor"]

logging:
  config: classpath:logback-boot.xml
jasypt:
  encryptor:
    password: easyrsa

elasticsearch-config:
  host: localhost
  port: 9200
  index: bookshop


